package io.nekohasekai.sagernet.bg.test

/** CountryNameToCode (src/global/CountryHelper.cpp, table include/global/CountryHelper.hpp): speedtest.net server countries. */
object CountryNames {

    /** The ISO code of a country name, "" when the desktop table has no entry for it. */
    @JvmStatic
    fun toCode(name: String?): String = CODES[name.orEmpty()] ?: ""

    private val CODES: Map<String, String> = hashMapOf(
        "Afghanistan" to "AF",
        "Aland Islands" to "AX",
        "Albania" to "AL",
        "Algeria" to "DZ",
        "American Samoa" to "AS",
        "Andorra" to "AD",
        "Angola" to "AO",
        "Anguilla" to "AI",
        "Antarctica" to "AQ",
        "Antigua And Barbuda" to "AG",
        "Argentina" to "AR",
        "Armenia" to "AM",
        "Netherlands Antilles" to "AN",
        "Aruba" to "AW",
        "Australia" to "AU",
        "Austria" to "AT",
        "Azerbaijan" to "AZ",
        "Bahamas" to "BS",
        "Bahrain" to "BH",
        "Bangladesh" to "BD",
        "Barbados" to "BB",
        "Belarus" to "BY",
        "Belgium" to "BE",
        "Belize" to "BZ",
        "Benin" to "BJ",
        "Bermuda" to "BM",
        "Bhutan" to "BT",
        "Bolivia" to "BO",
        "Bosnia And Herzegovina" to "BA",
        "Botswana" to "BW",
        "Bouvet Island" to "BV",
        "Brazil" to "BR",
        "British Indian Ocean Territory" to "IO",
        "Brunei Darussalam" to "BN",
        "Bulgaria" to "BG",
        "Burkina Faso" to "BF",
        "Burundi" to "BI",
        "Cambodia" to "KH",
        "Cameroon" to "CM",
        "Canada" to "CA",
        "Cape Verde" to "CV",
        "Cayman Islands" to "KY",
        "Central African Republic" to "CF",
        "Chad" to "TD",
        "Chile" to "CL",
        "China" to "CN",
        "Christmas Island" to "CX",
        "Cocos (Keeling) Islands" to "CC",
        "Colombia" to "CO",
        "Comoros" to "KM",
        "Congo" to "CG",
        "Congo, Democratic Republic" to "CD",
        "Cook Islands" to "CK",
        "Costa Rica" to "CR",
        "Cote D\"Ivoire" to "CI",
        "Croatia" to "HR",
        "Cuba" to "CU",
        "Cyprus" to "CY",
        "Czech Republic" to "CZ",
        "Denmark" to "DK",
        "Djibouti" to "DJ",
        "Dominica" to "DM",
        "Dominican Republic" to "DO",
        "Ecuador" to "EC",
        "Egypt" to "EG",
        "El Salvador" to "SV",
        "Equatorial Guinea" to "GQ",
        "Eritrea" to "ER",
        "Estonia" to "EE",
        "Ethiopia" to "ET",
        "Falkland Islands (Malvinas)" to "FK",
        "Faroe Islands" to "FO",
        "Fiji" to "FJ",
        "Finland" to "FI",
        "France" to "FR",
        "French Guiana" to "GF",
        "French Polynesia" to "PF",
        "French Southern Territories" to "TF",
        "Gabon" to "GA",
        "Gambia" to "GM",
        "Georgia" to "GE",
        "Germany" to "DE",
        "Ghana" to "GH",
        "Gibraltar" to "GI",
        "Greece" to "GR",
        "Greenland" to "GL",
        "Grenada" to "GD",
        "Guadeloupe" to "GP",
        "Guam" to "GU",
        "Guatemala" to "GT",
        "Guernsey" to "GG",
        "Guinea" to "GN",
        "Guinea-Bissau" to "GW",
        "Guyana" to "GY",
        "Haiti" to "HT",
        "Heard Island & Mcdonald Islands" to "HM",
        "Holy See (Vatican City State)" to "VA",
        "Honduras" to "HN",
        "Hong Kong" to "HK",
        "Hungary" to "HU",
        "Iceland" to "IS",
        "India" to "IN",
        "Indonesia" to "ID",
        "Iran, Islamic Republic Of" to "IR",
        "Iraq" to "IQ",
        "Ireland" to "IE",
        "Isle Of Man" to "IM",
        "Israel" to "IL",
        "Italy" to "IT",
        "Jamaica" to "JM",
        "Japan" to "JP",
        "Jersey" to "JE",
        "Jordan" to "JO",
        "Kazakhstan" to "KZ",
        "Kenya" to "KE",
        "Kiribati" to "KI",
        "Korea" to "KR",
        "Kuwait" to "KW",
        "Kyrgyzstan" to "KG",
        "Lao People\"s Democratic Republic" to "LA",
        "Latvia" to "LV",
        "Lebanon" to "LB",
        "Lesotho" to "LS",
        "Liberia" to "LR",
        "Libyan Arab Jamahiriya" to "LY",
        "Liechtenstein" to "LI",
        "Lithuania" to "LT",
        "Luxembourg" to "LU",
        "Macao" to "MO",
        "Macedonia" to "MK",
        "Madagascar" to "MG",
        "Malawi" to "MW",
        "Malaysia" to "MY",
        "Maldives" to "MV",
        "Mali" to "ML",
        "Malta" to "MT",
        "Marshall Islands" to "MH",
        "Martinique" to "MQ",
        "Mauritania" to "MR",
        "Mauritius" to "MU",
        "Mayotte" to "YT",
        "Mexico" to "MX",
        "Micronesia, Federated States Of" to "FM",
        "Moldova" to "MD",
        "Monaco" to "MC",
        "Mongolia" to "MN",
        "Montenegro" to "ME",
        "Montserrat" to "MS",
        "Morocco" to "MA",
        "Mozambique" to "MZ",
        "Myanmar" to "MM",
        "Namibia" to "NA",
        "Nauru" to "NR",
        "Nepal" to "NP",
        "Netherlands" to "NL",
        "New Caledonia" to "NC",
        "New Zealand" to "NZ",
        "Nicaragua" to "NI",
        "Niger" to "NE",
        "Nigeria" to "NG",
        "Niue" to "NU",
        "Norfolk Island" to "NF",
        "Northern Mariana Islands" to "MP",
        "Norway" to "NO",
        "Oman" to "OM",
        "Pakistan" to "PK",
        "Palau" to "PW",
        "Palestinian Territory, Occupied" to "PS",
        "Panama" to "PA",
        "Papua New Guinea" to "PG",
        "Paraguay" to "PY",
        "Peru" to "PE",
        "Philippines" to "PH",
        "Pitcairn" to "PN",
        "Poland" to "PL",
        "Portugal" to "PT",
        "Puerto Rico" to "PR",
        "Qatar" to "QA",
        "Reunion" to "RE",
        "Romania" to "RO",
        "Russian Federation" to "RU",
        "Rwanda" to "RW",
        "Saint Barthelemy" to "BL",
        "Saint Helena" to "SH",
        "Saint Kitts And Nevis" to "KN",
        "Saint Lucia" to "LC",
        "Saint Martin" to "MF",
        "Saint Pierre And Miquelon" to "PM",
        "Saint Vincent And Grenadines" to "VC",
        "Samoa" to "WS",
        "San Marino" to "SM",
        "Sao Tome And Principe" to "ST",
        "Saudi Arabia" to "SA",
        "Senegal" to "SN",
        "Serbia" to "RS",
        "Seychelles" to "SC",
        "Sierra Leone" to "SL",
        "Singapore" to "SG",
        "Slovakia" to "SK",
        "Slovenia" to "SI",
        "Solomon Islands" to "SB",
        "Somalia" to "SO",
        "South Africa" to "ZA",
        "South Georgia And Sandwich Isl." to "GS",
        "Spain" to "ES",
        "Sri Lanka" to "LK",
        "Sudan" to "SD",
        "Suriname" to "SR",
        "Svalbard And Jan Mayen" to "SJ",
        "Swaziland" to "SZ",
        "Sweden" to "SE",
        "Switzerland" to "CH",
        "Syrian Arab Republic" to "SY",
        "Taiwan" to "TW",
        "Tajikistan" to "TJ",
        "Tanzania" to "TZ",
        "Thailand" to "TH",
        "Timor-Leste" to "TL",
        "Togo" to "TG",
        "Tokelau" to "TK",
        "Tonga" to "TO",
        "Trinidad And Tobago" to "TT",
        "Tunisia" to "TN",
        "Turkey" to "TR",
        "Turkmenistan" to "TM",
        "Turks And Caicos Islands" to "TC",
        "Tuvalu" to "TV",
        "Uganda" to "UG",
        "Ukraine" to "UA",
        "United Arab Emirates" to "AE",
        "United Kingdom" to "GB",
        "United States" to "US",
        "United States Outlying Islands" to "UM",
        "Uruguay" to "UY",
        "Uzbekistan" to "UZ",
        "Vanuatu" to "VU",
        "Venezuela" to "VE",
        "Viet Nam" to "VN",
        "Virgin Islands, British" to "VG",
        "Virgin Islands, U.S." to "VI",
        "Wallis And Futuna" to "WF",
        "Western Sahara" to "EH",
        "Yemen" to "YE",
        "Zambia" to "ZM",
    )
}
